
[build]
  command = "npm run build || echo 'no build'"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/*"]

[[scheduled.functions]]
  name = "sync-events"
  # every 3 hours
  cron = "0 */3 * * *"
