[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless", "@netlify/blobs"]
  included_files = ["db/**"]

# Enable Identity (toggle in Netlify UI as well)

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
